apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: server-debug
    docker:
      dockerfile: docker/debug/Dockerfile
    context: .
    sync: 
      auto: true 
  local:
    push: true
    useDockerCLI: true
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yml
